In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset=pd.read_csv('C:/Users/SATYAJIT/Downloads/Match_Making.csv')

labels=dataset.iloc[:,-1].values
#print(labels)

features=dataset.iloc[:,0:2].values
#print(features)

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

features_train,features_test,labels_train,labels_test=train_test_split(features,labels,test_size=0.2)
classifier=SVC(kernel='poly')

classifier.fit(features_train,labels_train)
labels_predict=classifier.predict(features_test)

cm=confusion_matrix(labels_test,labels_predict)
print(cm)

#rbf kernel
#array([[19,  2],
#       [ 0, 79]], dtype=int64)

#poly kernel
#array([[15,  2],
#       [ 0, 83]], dtype=int64)



[[22  5]
 [ 4 69]]
